- name: Overwrite and Fix Device Tree
        run: |
          mkdir -p ~/twrp/device/everyphone/ep171en
          cp -rv $GITHUB_WORKSPACE/* ~/twrp/device/everyphone/ep171en/ || true
          
          cd ~/twrp/device/everyphone/ep171en
          echo 'PRODUCT_MAKEFILES := $(LOCAL_DIR)/omni_ep171en.mk' > AndroidProducts.mk
          echo 'add_lunch_combo omni_ep171en-eng' > vendorsetup.sh
          
          # パスを TWRP 7.1 の正解（build/target/）に修正したぞ！
          cat <<EOF > omni_ep171en.mk
          \$(call inherit-product, build/target/product/embedded.mk)
          \$(call inherit-product, vendor/omni/config/common.mk)
          PRODUCT_DEVICE := ep171en
          PRODUCT_NAME := omni_ep171en
          PRODUCT_BRAND := EveryPhone
          PRODUCT_MODEL := EP-171EN
          PRODUCT_MANUFACTURER := everyphone
          EOF

          sed -i 's/except IOError, ES.ParseError:/except (IOError, ES.ParseError):/g' ~/twrp/build/tools/roomservice.py
